updating gitignore

diff --git a/vendor/composer/composer/bin/composer b/vendor/composer/composer/bin/composer
--- a/vendor/composer/composer/bin/composer
+++ b/vendor/composer/composer/bin/composer
@@ -24,6 +24,12 @@ if (defined('HHVM_VERSION') && version_compare(HHVM_VERSION, '4.0', '>=')) {
     echo 'HHVM 4.0 has dropped support for Composer, please use PHP instead. Aborting.'.PHP_EOL;
     exit(1);
 }
+if (!extension_loaded('iconv') && !extension_loaded('mbstring')) {
+    echo 'The iconv OR mbstring extension is required and both are missing.'
+        .PHP_EOL.'Install either of them or recompile php without --disable-iconv.'
+        .PHP_EOL.'Aborting.'.PHP_EOL;
+    exit(1);
+}
 
 if (function_exists('ini_set')) {
     @ini_set('display_errors', '1');
@@ -57,6 +63,16 @@ if (function_exists('ini_set')) {
         unset($memoryInBytes);
     }
     unset($memoryLimit);
+}
+
+// Workaround PHP bug on Windows where env vars containing Unicode chars are mangled in $_SERVER
+// see https://github.com/php/php-src/issues/7896
+if (PHP_VERSION_ID >= 70113 && (PHP_VERSION_ID < 80016 || (PHP_VERSION_ID >= 80100 && PHP_VERSION_ID < 80103)) && Platform::isWindows()) {
+    foreach ($_SERVER as $serverVar => $serverVal) {
+        if (($serverVal = getenv($serverVar)) !== false) {
+            $_SERVER[$serverVar] = $serverVal;
+        }
+    }
 }
 
 Platform::putEnv('COMPOSER_BINARY', realpath($_SERVER['argv'][0]));
